---
AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation for Adevinta Spain SRE Challenge"

Parameters:
  Port:
    Type: Number
    Default: 80
  SubnetA:
    Type: String
  SubnetB:
    Type: String
  SubnetC:
    Type: String

  # Solution
  TargetGroupStackExportName:
    Type: String
    Description: The Target Group  Export Name to be used to send the traffic
    Default: TargetGroup

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: adevinta-spain-sre-challenge-elb
      Type: network
      IpAddressType: ipv4
      Scheme: internal
      Subnets:
        - !Ref SubnetA
        - !Ref SubnetB
        - !Ref SubnetC

  # Solution
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: !Ref Port
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Fn::ImportValue: !Sub "${TargetGroupStackExportName}:TargetGroupArn"
