---
AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation for Adevinta Spain SRE Challenge"

Parameters:
  VpcId:
    Type: String
  Port:
    Type: Number
    Default: 80
  Ip1:
    Type: String
    Default: 10.0.0.1
  Ip2:
    Type: String
    Default: 10.0.0.2
  Ip3:
    Type: String
    Default: 10.0.0.3

  # Solution
  StackExportName:
    Description: This value will be used to prefix the export values of the template
    Type: String
    Default: TargetGroup
    AllowedPattern: '[a-zA-Z0-9\-]+'
    MinLength: 2
    MaxLength: 40
    ConstraintDescription: Must be in lower or upper case character, "-" is allowed and digit from 0 to 9.  Maximun 40 characters

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: adevinta-spain-sre-challenge-tg
      Port: !Ref Port
      Protocol: TCP
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: !Ref Port
      HealthCheckProtocol: TCP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      TargetType: ip
      Targets:
        - Id: !Ref Ip1
          Port: !Ref Port
          AvailabilityZone: all
        - Id: !Ref Ip2
          Port: !Ref Port
          AvailabilityZone: all
        - Id: !Ref Ip3
          Port: !Ref Port
          AvailabilityZone: all
      VpcId: !Ref VpcId

# Solution
Outputs:
  TargetGroupArn:
    Description: Target Group ARN
    Value: !Ref TargetGroup
    Export:
      Name: !Join [":", [!Ref StackExportName, TargetGroupArn]]
