---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation for Adevinta Spain SRE Challenge'

Parameters:
  VpcId:
    Type: String
  Port:
    Type: Number
    Default: 80
  SubnetA:
    Type: String
  SubnetB:
    Type: String
  SubnetC:
    Type: String

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: adevinta-spain-sre-challenge-elb
      Type: network
      IpAddressType: ipv4
      Scheme: internal
      Subnets:
        - !Ref SubnetA
        - !Ref SubnetB
        - !Ref SubnetC      
  Listener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: !Ref Port
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !GetAtt TargetGroupStack.Outputs.TargetGroupArn
  TargetGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cloudformation-stack-1.yaml
      Parameters:
        VpcId: !Ref VpcId